[package]
name = "orchidron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcontainer = { version = "0.1.0" }
nix = "0.26.2"
